// <auto-generated />
namespace SkopjeCS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newM));
        
        string IMigrationMetadata.Id
        {
            get { return "202012202138019_newM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
