version: '3.4'

services:
  coordinatelocation:
    image: coordinatelocation:dev
    container_name: CoordinateLocation
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "CoordinateLocation"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_coordinatelocation$
    volumes:
      - C:\Users\Blagica\Desktop\New folder\SkopjeChargingStations\Domasna4\Demo\CoordinateLocation:/app
      - C:\Users\Blagica\Desktop\New folder\SkopjeChargingStations\Domasna4\Demo:/src
      - C:\Users\Blagica\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_coordinatelocation$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_coordinatelocation$ \"/app/bin/Debug/netcoreapp3.1/CoordinateLocation.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  demo:
    image: demo:dev
    container_name: Demo
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Demo"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_demo$
    volumes:
      - C:\Users\Blagica\Desktop\New folder\SkopjeChargingStations\Domasna4\Demo\Demo:/app
      - C:\Users\Blagica\Desktop\New folder\SkopjeChargingStations\Domasna4\Demo:/src
      - C:\Users\Blagica\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_demo$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_demo$ \"/app/bin/Debug/netcoreapp3.1/Demo.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
